file <- read.table("household_power_consumption.txt",header = T, sep = ";",na.strings = "?")
file$Date <- as.Date(file$Date,format = "%d/%m/%Y")
data <- subset(file, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
data$DateTime <- as.POSIXct(paste(data$Date, data$Time))
png(filename = 'plot3.png',width = 480,height = 480)
Sys.setlocale("LC_ALL", "english")
plot(data$DateTime, data$Sub_metering_1, xlab = '', ylab = 'Energy sub metering', type = 'l')
lines(data$DateTime, data$Sub_metering_2, col = 'red')
lines(data$DateTime, data$Sub_metering_3, col = 'blue')
legend('topright',col = c('black','red','blue'),legend = c('Sub_Metering_1' , 'Sub_Metering_2' , 'Sub_Metering_3'))
dev.off()